image: Visual Studio 2015

platform:
    - x86
    - x64

configuration: Release

build:
    parallel: true

build_script:
    - cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=install
    - cmake --build build
    - cmake --build build --target install
    - cmake -H. -Bbuild -DCPACK_GENERATOR=WIX 
    - cmake --build build --target package

artifacts:
    - path: install\packages\*.msi
      name: solver

deploy:
    description: 'Some minor fixes'
    provider: GitHub
    auth_token:
        secure: JlidwpidFVECcpXIQQoOIsrKYUMY7uY48WUxzRbXj6fzqsOiO18FSMXCsJ8mUuOF
    draft: false
    prerelease: false
    on:
        APPVEYOR_REPO_TAG: true
